apiVersion: apps/v1
kind: Deployment
metadata:
  name: async-logger
  namespace: async-logger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: async-logger
  template:
    metadata:
      labels:
        app: async-logger
    spec:
      containers:
        - name: async-logger
          image: eddyjayiseh/async-logger:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
