apiVersion: v1
kind: Service
metadata:
  name: async-logger-svc
  namespace: async-logger
spec:
  selector:
    app: async-logger
  ports:
    - name: http
      port: 8080       # service port
      targetPort: 8080 # container port
  type: ClusterIP      # we’ll access it via port-forward
